ALTER TABLE items
  ADD COLUMN status ENUM('IN_USE','MAINTENANCE','AVAILABLE','UNAVAILABLE','UNSERVICEABLE') NOT NULL DEFAULT 'AVAILABLE' AFTER active,
  ADD COLUMN `condition` ENUM('EXCELLENT','GOOD','FAIR','POOR','DAMAGED') NOT NULL DEFAULT 'GOOD' AFTER status;

ALTER TABLE stock_tx
  ADD COLUMN item_status_before ENUM('IN_USE','MAINTENANCE','AVAILABLE','UNAVAILABLE','UNSERVICEABLE') NULL AFTER user_id,
  ADD COLUMN item_status_after ENUM('IN_USE','MAINTENANCE','AVAILABLE','UNAVAILABLE','UNSERVICEABLE') NULL AFTER item_status_before,
  ADD COLUMN item_condition_before ENUM('EXCELLENT','GOOD','FAIR','POOR','DAMAGED') NULL AFTER item_status_after,
  ADD COLUMN item_condition_after ENUM('EXCELLENT','GOOD','FAIR','POOR','DAMAGED') NULL AFTER item_condition_before;
